<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ftec.ProjetosWeb.Pagamento.Dominio\Ftec.ProjetosWeb.Pagamento.Dominio.csproj" />
    <ProjectReference Include="..\Ftec.ProjetosWeb.Pagamento.Persistencia\Ftec.ProjetosWeb.Pagamento.Persistencia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
